config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # the only suggestion for improvement i have are about consistent indentation
  # again your planning/ERDs make for very well-thought out routes. fantastic!

  root to: "categories#index"

  resources :categories, only: [:index, :show] #nice

  # nice solution to getting around triply nest-resources
  resources :recipes do
    resources :comments, except: :index
  end

  resources :categories do
    resources :recipes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  # Just putting in my general comments regarding your models here
  # Your ERDs are well-thought out, and your associations make sense. there are
  # a lot of them, but they are sensible.
end

app/models/category.rb
class Category < ApplicationRecord
  # nice, you could also convert this to a many-to-many, but you'd have to add an additional model called categorizations that links a category to a recipe.
  has_many :recipes
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
  
  # validates :title, :author, :body, :presence => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :comments
  # nice! I would definitely add in validations later. great thought!
  # validates :title, :ingredients, :img_url, :directions, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
  has_many :comments 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @recipe = Recipe.new
    @recipes = Recipe.where(params[:category_id] == @category)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, only:[:create, :destroy]

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.new
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])

    # nice use of unless! very ruby
    unless @comment.user == current_user
      flash[:alert] = "Only the author can delete this comment!"
    end
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])
    # you can validate like this:
    if @comment.update(comment_params)
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = "input is required!"
      render :edit
    end
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.create!(comment_params.merge(user: current_user))
    # if validates?
    redirect_to recipe_path(@recipe)
    # else
    #   flash[:alert] = "input is required!"
    #   render :new
    # end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to recipe_path(@recipe)
  end

  private
  def comment_params
    params.require(:comment).permit(:author, :title, :body)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!, only:[:create, :destroy]
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
    unless @recipe.user == current_user
      # nice UX!
      flash[:alert] = "Only the Chef can edit this Recipe!"
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)

    # see my comment in the comments_controller on validations
    redirect_to recipe_path
  end

  def create
    @category = Category.find(params[:category_id])
    @recipe = @category.recipes.create!(recipe_params.merge(user: current_user))
    # if validates?
    redirect_to category_path(@category)
    # else
    #   flash[:alert] = "input is required!"
    #   render :new
    # end
  end

  def destroy

    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
      @recipe.destroy
    else
      flash[:alert] = "Only the Chef can delete this Recipe!"
    end
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :ingredients, :img_url, :directions)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h2 class="welcome"> Welcome to Recipe Ting! The place where the people are friendly and the dishes are scrumptous!</h2>


<% @categories.each do |category| %>
  <div class="category">
    <p><%=category.name %><a href="/categories/<%= category.id %>"></p><img class= "this" src="<%= category.img_url %>"></a></p>
  </div>

  <% end %>

app/views/categories/show.html.erb
<h2 class="cname"><%= @category.name %></h2>

<% if current_user %>
  <h3 class="addrecipe"><%=link_to "Add Recipe", new_category_recipe_path(@category) %></h3>
<% end %>

<% @category.recipes.each do |recipe| %>
<div class="recipe">
  <div class="food">
    <a href="/recipes/<%= recipe.id %>"><img class="rimage" src="<%= recipe.img_url %>"></a>
      <p class="rtitle"><%= recipe.title %></p>
  </div>
</div>


<%end %>

app/views/comments/_form.html.erb
<!-- Nice partial! -->
<%= form_for [@recipe, @comment] do |f| %>
  <%= f.label :title %><br />
  <%= f.text_field :title %><br />

  <%= f.label :author %><br />
  <%= f.text_field :author %><br />

  <%= f.label :body %><br />
  <%= f.text_area :body %><br />

  <%=f.submit %><br />
<% end %>
<br />
<br />
  <%= form_for [@recipe, @comment], method: :delete do |f| %><br>
     <%= f.submit "Delete!", class: "delete" %><br />
  <% end %>

app/views/comments/edit.html.erb
<h3>Edit Comment</h3>

<%= render "form"%> 

app/views/comments/new.html.erb
<h3>Add New Comment</h3>

<%= render "form" %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe Ting</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <h1><a href="/categories">RECIPE TING!</a> </h1>

  <!-- Well-designed application layout! -->
  
  <% if !current_user %>
    <h2 class="registration"><%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %></h2>
  <% else %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <%= current_user.email %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/recipes/edit.html.erb
<h3>Edit Recipe</h3>

<%= form_for @recipe do |f| %>
  <%= f.label :title %><br />
  <%= f.text_field :title %><br />

  <%= f.label :ingredients %><br />
  <%= f.text_area :ingredients %><br />

  <%= f.label :directions %><br />
  <%= f.text_area :directions %><br />

  <%= f.label :img_url %><br />
  <%= f.text_field :img_url %><br />
<br />
<%= f.submit %>
<% end %><br />

<%= form_for @recipe, method: :delete do |f| %>
  <%= f.submit "Delete", class: "delete" %><br />
  <% end %>

app/views/recipes/index.html.erb
<h3 class="allrecipes"><%= link_to "All Recipes", recipes_path %></h3>


<% @recipes.each do |recipe| %>
  <div class="recipe">
    <div class="food">
      <img class="rimage" src="<%= recipe.img_url %>">
        <a href="/recipes/<%= recipe.id %>"><p class="rtitle"><%= recipe.title %></a></p>
      </div>
    </div>
 <% end %>

app/views/recipes/new.html.erb
<h3>Share your Favorite Recipes and help us expand our tastebuds!</h3>

<%= form_for([@category, @recipe]) do |f| %>
  <%= f.label :title %><br />
  <%= f.text_field :title %><br />

  <%= f.label :ingredients %><br />
  <%= f.text_area :ingredients %><br />

  <%= f.label :directions %><br />
  <%= f.text_area :directions %><br />

  <%= f.label :img_url %><br />
  <%= f.text_field :img_url %><br />

  <%= f.submit %>
  <% end %>

app/views/recipes/show.html.erb
<h2><%= @recipe.title %></h2>

  <div class="showrecipe">
    <img class="rimage" src="<%= @recipe.img_url %>">
      <h3>Ingredients</h3>
      <ul>
        <% @recipe.ingredients.split(", ").each do |i| %>
          <div style="white-space: pre-line;">
            <li><%= i %></li>
        <% end %>
        </div>
      </ul>
      <h3>Directions</h3>
        <ul id="instructions">
          <!-- Clever! Sometimes, commas might not be separators between actual steps. "Quickly, crack 3 eggs and whisk" There "Quickly" would be treated by your code as its own step; you might be able to add in a check to see if it's one word item. I really like the thought behind this feature regardless! -->
            <% @recipe.directions.split(", ").each do |i| %>
              <div style="white-space: pre-line;">
                <li><%= i %></li>
              <% end %>
        </ul>
      </div>
  </div>

<h6><%= link_to "Edit Recipe", edit_recipe_path%> | <%= link_to "Delete Recipe", recipe_path, method: :delete %></h6>

<h4>Comments <%= link_to "New Comment", new_recipe_comment_path(@recipe) %></h4>

 <% @recipe.comments.each do |comment| %>
    <div>
      <h4><%= comment.title %></h4>
      <p><%= comment.body %></p>
      <h5><%= comment.author %>, <%= comment.updated_at %></h5>
      <% if (comment.user == current_user) && current_user %>
      <h6><%= link_to "Edit Comment", edit_recipe_comment_path(@recipe,comment) %>  | <%= link_to "Delete Comment", recipe_comment_path(@recipe, comment), method: :delete %></h6>
      <% end %>
    </div>
  <% end %>